
---
title: skeleton.qmd
date: last-modified
---
#   TAGS:   TidyTuesday, juliasilge, inner_join, tidyverse, 8j

# https://juliasilge.com/blog/polling-places/
# https://www.youtube.com/watch?v=NZ2oXAj-bHE&list=PLbcglKxZP5PN07Vw-0ukcDJCxFGY2Crgc&index=11

```{r}
library(tidyverse)
# big !

if (F) {
polling_places <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-01-16/polling_places.csv')
saveRDS(polling_places,   file="polling_places.RDS")
}
polling_places  <- readRDS(file = "polling_places.RDS")
names(polling_places)
#  [1] "election_date"     "state"             "county_name"      
#  [4] "jurisdiction"      "jurisdiction_type" "precinct_id"      
#  [7] "precinct_name"     "polling_place_id"  "location_type"    
# [10] "name"              "address"           "notes"            
# [13] "source"            "source_date"       "source_notes"     
nrow(polling_places) # [1] 461445

head(polling_places)

polling_places |> 
  count(election_date)                 # each date, # polling places

```

##  By State, changes in # polling places by year
```{r}
polling_places |> 
  dplyr::filter(month(election_date) == 11) |> 
  count(state, election_date) |>
  mutate(state = fct_reorder(state, n)) |> 
  ggplot(aes(election_date, n, color = state)) + 
  geom_line(alpha = 0.6, linewidth = 1.2, show.legend = FALSE) + 
  scale_color_viridis_d() +
  scale_y_log10() +
  labs(x = NULL, y = "Number of polling places per state")
```

## save 
```{r}
by_state <-
  polling_places |> 
  dplyr::filter(month(election_date) == 11) |> 
  count(state, election_date)

by_state

total_change <-
  by_state |> 
  group_by(state) |> 
  mutate(change = n - dplyr::lag(n)) |>     # compare to prior value of n|
  dplyr::filter(n() > 1)  |>    # omit states with only 1 election_date
  summarize(change = sum(change, na.rm = TRUE) / first(n)) 

total_change


summary(total_change$change)
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#  -0.834  -0.070  -0.007  -0.045   0.024   0.594 
```
```{r}

us_states <- as_tibble(ggplot2::map_data("state"))
limits <- max(abs(total_change$change)) * c(-1, 1)
str(us_states)  # region="alabama" etc
str(total_change)  # state = "AK"  etc
```
```{r}
us_states |> 
  inner_join(tibble(state = state.abb, region = str_to_lower(state.name))) |> 
  left_join(total_change) |> 
  ggplot(aes(x = long, y = lat, group = group, fill = change)) +
  geom_polygon(color = "black", linewidth = 0.1) +
  coord_map() +
  scale_fill_distiller(palette = "RdYlBu", direction = 1, na.value = "gray95",
                       limits = limits, label = scales::label_percent()) +
  labs(fill = "Total change")
```




vim:linebreak:nospell:nowrap:cul tw=78 fo=tqlnrc foldcolumn=1 cc=+1
